#ifndef INKCANVAS_GLOBAL_H
#define INKCANVAS_GLOBAL_H

#ifdef INKCANVAS_QT
#  define INKCANVAS_NAMESPACE InkCanvasQt
#elif defined INKCANVAS_CORE
#  define INKCANVAS_NAMESPACE InkCanvasCore
#else
#  define INKCANVAS_QT 1
#  define INKCANVAS_NAMESPACE InkCanvasQt
#endif

#if !defined INKCANVAS_CORE && defined INKCANVAS_QT
#  define INKCANVAS_QT_SIGNALS
#  define INKCANVAS_QT_DRAW
#endif

#ifdef INKCANVAS_QT
#  include <QtCore/qglobal.h>
#else
#  define Q_DECL_EXPORT
#  define Q_DECL_IMPORT
#endif

#if defined(INKCANVAS_LIBRARY)
#  define INKCANVAS_EXPORT Q_DECL_EXPORT
#else
#  define INKCANVAS_EXPORT Q_DECL_IMPORT
#endif

#ifdef INKCANVAS_NAMESPACE
#  define INKCANVAS_BEGIN_NAMESPACE namespace INKCANVAS_NAMESPACE {
#  define INKCANVAS_END_NAMESPACE }
#  define INKCANVAS_USE_NAMESPACE using namespace ::INKCANVAS_NAMESPACE;
#  define INKCANVAS_PREPEND_NAMESPACE(name) ::INKCANVAS_NAMESPACE::name
#  define INKCANVAS_FORWARD_DECLARE_CLASS(name) \
   INKCANVAS_BEGIN_NAMESPACE class name; INKCANVAS_END_NAMESPACE \
   using INKCANVAS_PREPEND_NAMESPACE(name);
#else
#  define INKCANVAS_BEGIN_NAMESPACE
#  define INKCANVAS_END_NAMESPACE
#  define INKCANVAS_USE_NAMESPACE
#  define INKCANVAS_PREPEND_NAMESPACE(name) ::name
#  define INKCANVAS_FORWARD_DECLARE_CLASS(name) class name
#endif

#endif // INKCANVAS_GLOBAL_H
