#ifndef INKCANVAS_GLOBAL_H
#define INKCANVAS_GLOBAL_H

#ifdef INKCANVAS_CORE
#define Q_DECL_EXPORT
#define Q_DECL_IMPORT
#define INKCANVAS_NAMESPACE InkCanvasCore
#else
#include <QtCore/qglobal.h>
#define INKCANVAS_NAMESPACE InkCanvasQt
#define INKCANVAS_QT 1
#endif

#if defined(INKCANVAS_LIBRARY)
#  define INKCANVAS_EXPORT Q_DECL_EXPORT
#else
#  define INKCANVAS_EXPORT Q_DECL_IMPORT
#endif

#ifdef INKCANVAS_NAMESPACE
# define INKCANVAS_BEGIN_NAMESPACE namespace INKCANVAS_NAMESPACE {
# define INKCANVAS_END_NAMESPACE }
# define INKCANVAS_USE_NAMESPACE using namespace ::INKCANVAS_NAMESPACE;
# define INKCANVAS_PREPEND_NAMESPACE(name) ::INKCANVAS_NAMESPACE::name
# define INKCANVAS_FORWARD_DECLARE_CLASS(name) \
   INKCANVAS_BEGIN_NAMESPACE class name; INKCANVAS_END_NAMESPACE \
   using INKCANVAS_PREPEND_NAMESPACE(name);
#else
# define INKCANVAS_BEGIN_NAMESPACE
# define INKCANVAS_END_NAMESPACE
# define INKCANVAS_USE_NAMESPACE
# define INKCANVAS_PREPEND_NAMESPACE(name) ::name
# define INKCANVAS_FORWARD_DECLARE_CLASS(name) class name
#endif

#endif // INKCANVAS_GLOBAL_H
